# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 786cb26623d6d1898196d95b20af8cb7aa3d352b8616287f6fbbc0ea54a192be7944b248d5803e28d44c56a36a77fe2beee4ff2b0233f9a98e7d11dd9bf0971b

test:
  secret_key_base: 8f3c1b868d63c352ea1ab694bb52fda5d85aa60e1b2836fb928be79abbc1cda8953f0f14c6a6a23fc6f1ef7e305ba553962e1e5d1e971974737701225d807e30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
